//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiadosaOrg
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFEvent
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> MFLocationId { get; set; }
        public string URL { get; set; }
        public string AuxField { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> DateTimeEntered { get; set; }
        public bool Current { get; set; }
    }
}
